### ISSUE TITLE
Devices are lost if disconnected or laptop slept

### ISSUE THREAD

**Issue by tunix** [flathub/io.github.pwr_solaar.solaar#33]
I don't remember this happening before the flatpak package. It's kind of hard to explain but I'll try my best ☺️

## Case 1

Turn off devices (MX Keys Mini + MX Vertical) and turn back on. Devices will not be shown inside Solaar until it's restarted. I think, if there are no devices, solaar doesn't show its tray icon. This causes the user to think it's not working. So when you start solaar it shows its main window with no devices. Restarting solaar makes everything work back again.

## Case 2

Close laptop lid and let it sleep. Solaar will not detect devices and you'll most probably have to restart it again to make things work.

**Comment by madness742** [comment]
I'm having the  same issue, but only when using a bluetooth connection. It doesn't happen when using the Bolt receiver.

Solaar also needs to be restarted when configured to autostart on boot with a bluetooth connection.

**Comment by tunix** [comment]
I didn't have the udev rule, tried adding it. But it didn't fix the problem. Removed the flatpak and installed solaar + solaar-udev packages (Fedora) and it works as it should now.

**Comment by francoism90** [comment]
Did you tried the updated udev rules? I believe this is fixed upstream.

**Comment by tunix** [comment]
> Did you tried the updated udev rules? I believe this is fixed upstream.

When where they released? Should I do anything or they come ootb with an update?

**Comment by francoism90** [comment]
@tunix You need to manually copy the udev rules. See my #35 for details.

**Comment by madness742** [comment]
> Did you tried the updated udev rules? I believe this is fixed upstream.

I've updated my udev rules, and I'm still experiencing this bug when using a bluetooth connection. Not sure if this is relevant but I'm using the bluetooth on my motherboard (MSI MAG B650 TOMAHAWK WIFI).

**Comment by ja02** [comment]
I am facing the same issue and I believe it's because of [this line in the pack script](https://github.com/flathub/io.github.pwr_solaar.solaar/blob/master/io.github.pwr_solaar.solaar.yaml#L16), which is commented out and thus keeps the feature disabled.

From the comments in [the related Issue](https://github.com/flathub/io.github.pwr_solaar.solaar/issues/7) it seems to me that at that time it made sense, as some manual actions were necessary to make things work. Maybe it just needs to be uncommented now? 😁🤷🏻‍♂️
